### ISSUE TITLE
Some compile warnings

### ISSUE THREAD

**Issue by tarsius** [vermiculus/apiwrap.el#4]
```
In toplevel form:
tests.el:24:9:Warning: reference to free variable ‘issue’
tests.el:31:1:Warning: value returned from (= (alist-get (quote id) my-issue)
    (alist-get (quote id) (car all-issues))) is unused

In end of data:
tests.el:39:1:Warning: the following functions are not known to be defined:
    defapiget-my-github-wrapper, repo,
    my-github-wrapper-get-repos-owner-repo-issues-number,
    my-github-wrapper-get-repos-owner-repo-issues,
    my-github-wrapper-get-repos-owner-repo-issues-number-comments
```

Also you might want to put the tests in a subdirectory and add a file `.nosearch` in it to keep it off the `load-path` (when using `normal-top-level-add-to-load-path` or my `borg` package manager, and to help the tools used to maintain the Emacsmirror).

**Comment by vermiculus** [comment]
> put the tests in a subdirectory and add a file `.nosearch` in it

Will do! That will stop it from compiling too, right? Or should I fix the compiling as well? It works when interpreted which is all I really cared about for these tests.
