### ISSUE TITLE
Apiwrap 0.2 fails to build from source on Debian unstable/sid

### ISSUE THREAD

**Issue by mfvescovi** [vermiculus/apiwrap.el#6]
Hi Sean!

While trying to build apiwrap 0.2 to upgrade the 0.1.2 version actually in Debian archives, I've faced the following error regarding tests:

>Running 4 tests (2017-08-21 21:32:46+0000)
   passed  1/4  apiwrap-macros
   passed  2/4  apiwrap-plist-to-alist
   passed  3/4  apiwrap-resolve-params
Test apiwrap-usage backtrace:
  test-get-some-method()
  (list (test-get-some-method) (test-request "/some/method"))
  (let ((fn-19 (function equal)) (args-20 (list (test-get-some-method)
  (lambda nil (let ((fn-19 (function equal)) (args-20 (list (test-get-
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test apiwrap-usage nil (lambda nil (let 
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test a
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test apiwrap-usage condition:
    (void-function nil)
   FAILED  4/4  apiwrap-usage

>Ran 4 tests, 3 results as expected, 1 unexpected (2017-08-21 21:32:47+0000)

>1 unexpected results:
   FAILED  apiwrap-usage

>dh_elpa_test: emacs -batch -Q -l package --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa\")" --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\")" -f package-initialize -L . -L test -l test/apiwrap-test.el --eval \(ert-run-tests-batch-and-exit\) returned exit code 1
debian/rules:4: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
--------------------------------------------------------------------------------
>Build finished at 2017-08-21T21:32:47Z

Any chance to figure out what's wrong there? Does it build fine for you?

Thanks in advance for your help.

**Comment by vermiculus** [comment]
It looks like I didn't update tests in 1ae3aa87cb198951f744b4246faae7f1c35f859d. The package is fine; just the tests are broken :) I'll push a patch sometime today.
