### ISSUE TITLE
Please bump 'Package-Version:' to 0.3

### ISSUE THREAD

**Issue by mfvescovi** [vermiculus/apiwrap.el#7]
.el file actually reports ';; Package-Version: 0.2' so packaging it would lead to wrong versioning.
In case, drop current release tag and re-tag the correcting commit.
Thanks.

**Comment by vermiculus** [comment]
ugh, yes. I have a really bad history of doing this. I'll fix and look into some pre tag hook to make sure it doesn't happen again.

**Comment by vermiculus** [comment]
Fixed in amended commit 5d25972192cd34553997ba193c09eab093a2b870
